name: tplatfom
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  lottie: ^1.4.3
  package_info_plus: ^1.4.3+1
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.6
  dio:
  go_router: ^3.1.1
  flutter_riverpod: ^1.0.3
  equatable:
  flutter_secure_storage:

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/logo/english_logo.svg
    - assets/images/login_background.png
    - assets/images/social/apple_logo.svg
    - assets/images/social/google_logo.svg
    - assets/images/social/facebook_logo.svg
    - assets/images/logo/get_started_icon.svg
    - assets/images/logo/qr_code.svg
    - assets/images/logo/letter_icon.svg
    - assets/images/logo/done_icon.svg
    - assets/images/logo/link_off_icon.svg
    - assets/images/logo/vector_icon.svg
    - assets/images/
    - assets/lottie/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
    - family: MobilePlatformIcons
      fonts:
        - asset: assets/fonts/MobilePlatformIcons.ttf
    - family: MobilePlatformIcons2
      fonts:
        - asset: assets/fonts/MobilePlatformIcons2.ttf
